version: "3.8"

services:
  app:
    image: aashishrepo/qpassignment:1.0
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/basics?allowPublicKeyRetrieval=true
      - spring.datasource.username=aashish
      - spring.datasource.password=aashish
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:latest"
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: qp
      MYSQL_USER: aashish
      MYSQL_PASSWORD: aashish
      MYSQL_ROOT_PASSWORD: root